services:
  - type: web
    name: the-gang
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: CLIENT_URL
        value: "*"
    autoDeploy: true
