services:
  - type: web
    name: the-gang
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CLIENT_URL
        value: "*"
    autoDeploy: true
