services:
  - type: web
    name: the-gang
    env: node
    plan: free
    branch: main
    buildCommand: bash ./render-build.sh
    startCommand: npm start
    envVars:
      - key: CLIENT_URL
        value: "*"
    autoDeploy: true
